web/router.ex
defmodule LearnReact.Router do
  use LearnReact.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :admin do
    plug :require_ownership
  end

  pipeline :tracking do
    plug :put_uri_on_session
  end

  scope "/", LearnReact do
    pipe_through :browser
    pipe_through :tracking

    resources "/lessons", LessonController, only: [:show]
    resources "/courses", CourseController, only: [:index, :show]
    resources "/charges", ChargeController, only: [:create]

    get "/", CourseController, :index
  end

  scope "/admin", LearnReact do
    pipe_through :browser
    pipe_through :admin

    resources "/lessons", LessonController, only: [:new, :create, :edit, :update, :delete]
    resources "/courses", CourseController, only: [:new, :create, :edit, :update, :delete]
    resources "/users", UserController
    resources "/charges", ChargeController, only: [:index, :show]
    resources "/purchases", PurchaseController
  end

  scope "/auth", LearnReact do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback

    delete "/logout", AuthController, :delete
  end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

  defp put_uri_on_session(conn, _) do
    conn
    |> put_session(:last_request_path, conn.request_path)
  end

  defp require_ownership(conn, _params) do
    user = get_session(conn, :current_user)

    if User.is_chan(user) do
      conn
    else
      conn
      |> redirect(to: "/") # TODO: 404 instead?
    end
  end
end

web/views/layout_view.ex
defmodule LearnReact.LayoutView do
  import LearnReact.PageTitle
  import LearnReact.PageName
  import LearnReact.PageDescription
  import LearnReact.CourseTitle
  import LearnReact.LessonTitle

  use LearnReact.Web, :view
end

web/templates/layout/_analytics.html.eex
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56273983-1', 'auto');
  ga('send', 'pageview');

</script>

web/templates/layout/_newsletter.html.eex
<div id="mc_embed_signup">
  <form
    action="//learnreact.us9.list-manage.com/subscribe/post?u=03b6ee2f58c8b4427c8ba9735&amp;id=f97aebbc64"
    method="post"
    id="mc-embedded-subscribe-form"
    name="mc-embedded-subscribe-form"
    class="validate"
    target="_blank"
    novalidate
  >
    <div
      id="mc_embed_signup_scroll"
      class="d-f length-30e"
    >
      <div class="mc-field-group fg-1 fs-1 fb-0%">
        <label for="mce-EMAIL">
          <input
            type="email"
            value=""
            name="EMAIL"
            class="required email w-100% text-input bc-gray6"
            id="mce-EMAIL"
            placeholder="Email address"
          >
        </label>
      </div>

      <div
        id="mce-responses"
        class="clear"
      >
        <div
          class="response"
          id="mce-error-response"
          style="display:none"
        ></div>

        <div
          class="response"
          id="mce-success-response"
          style="display:none"
        ></div>
      </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->

      <div
        style="position: absolute; left: -5000px;"
        aria-hidden="true"
      >
        <input
          type="text"
          name="b_03b6ee2f58c8b4427c8ba9735_f97aebbc64"
          tabindex="-1"
          value=""
        >
      </div>

      <div class="clear">
        <input
          type="submit"
          value="Subscribe"
          name="subscribe"
          id="mc-embedded-subscribe"
          class="button btn ml-2 gc-blue5 bc-blue5 c-white fw-b"
        >
      </div>
    </div>
  </form>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="name" content="<%= page_name(assigns)%>">
    <meta name="description" content="<%= page_description(assigns)%>">
    <meta name="author" content="Michael Chan @chantastic">

    <title><%= page_title(assigns) %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="ff-system-sans xw-60e m-0a p-2">
    <%= if get_flash(@conn, :failure) do %>
      <p class="gc-red7 c-white py-1 px-2" role="alert"><%= get_flash(@conn, :failure) %></p>
    <% end %>

    <%= if get_flash(@conn, :error) do %>
      <p class="gc-red7 c-white py-1 px-2 ta-c" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>

    <%= if get_flash(@conn, :info) do %>
      <p class="gc-blue5 c-white py-1 px-2 ta-c" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>

    <header
      class="mb-3 bc-gray3 bw-0 bs-s d-f ai-c"
      style="border-bottom-width: 1px"
    >
      <div class="fg-1 fs-1 fb-0%">
        <h3
          class="fw-800 c-gray6"
          style="display: inline-block"
        >
          <%= link to: "/", class: "breadcrumb-link c-gray7" do %>
            Learn React
          <% end %>
        </h3>

        <h5
          class="fw-800 c-gray6"
          style="display: inline-block"
        >
          <%= if course_title(assigns) do %>
            <span>&nbsp;/&nbsp;</span>
            <%= link to: course_path(@conn, :show, @course), class: "breadcrumb-link c-gray7" do %>
              <%= course_title(assigns) %>
            <% end %>
          <% end %>

          <%= if lesson_title(assigns) do %>
            <span>&nbsp;/&nbsp;</span>
            <%= link to: lesson_path(@conn, :show, @lesson), class: "breadcrumb-link c-gray7" do %>
              <%= lesson_title(assigns) %>
            <% end %>
          <% end %>
        </h4>
      </div>

      <div style="display: none">
        <%= if @current_user do %>
          <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn" %>
        <% else %>
          <a href="/auth/github" class="btn">Sign in with Github</a>
        <% end %>
      </div>
    </header>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer
      class="mt-3 pt-3 bw-0 bs-s bc-gray3"
      style="border-top-width: 1px"
    >
      <%= if !@current_user do %>
        <div class="mb-2">
          <%= render "_newsletter.html" %>
        </div>
      <% end %>

      <small class="c-gray5 td-i"><em>&copy; Copyright 2017, Michael Chan</em></small>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <%= if Mix.env == :prod do %>
      <%= render "_analytics.html" %>
    <% end %>
  </body>
</html>