config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :courses
    resources :lessons
    resources :purchases
  end

  resources :courses, only: [:index, :show] do
    scope module: "courses" do
      resources :purchases, only: [:new, :create]
    end
  end
  resources :lessons, only: [:index, :show]
  resources :purchases, only: [:index]
  resources :subscriptions, only: [:new] do
    get 'successful', on: :new # REST exception for analytics tracking
  end

  namespace :my do
    resource :subscription, only: [:show]
  end

  namespace :stripe do
    resources :webhook, only: :create
  end

  root "courses#index"

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/controllers/my/subscriptions_controller.rb
module My
  class SubscriptionsController < ApplicationController
    include SessionsHelper

    before_action :set_session_return_to

    def show
      user = MySubscriptionUser.new(current_user)
      @subscription = user.subscription
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout "subscription"
  
  include SessionsHelper

  before_action :set_session_return_to

  def new
    # if user_signed_in?
    #   @purchases = Purchase.where(user: current_user)
    # else
    #   raise ActionController::RoutingError.new('Not Found')
    # end
  end

  def show
    @subscription = Subscription.find(params[:id])

    # @course = Course.find_by!(slug: params[:id])
  end

  def create
    authenticate_user!

    # store retrievable customer on user model
    customer =
      if current_user.customer_token.present?
        Stripe::Customer.retrieve(current_user.customer_token)
      else
        Stripe::Customer.create(
          :email => params[:stripeEmail],
          :source  => params[:stripeToken],
        )
      end

    stripe_subscription = Stripe::Subscription.create(
      :customer    => customer.id,
      :items => [{
        :plan => "yearly-36"
      }]
    )

    @subscription = Subscription.new(
      :subscription_token => stripe_subscription.id,
      :user_id => current_user.id,
    )

    ActiveRecord::Base.transaction do
      current_user.update(customer_token: customer.id)
      @subscription.save
    end

    redirect_to successful_new_subscription_path, :notice => "Charge succeeded!"

  rescue Stripe::CardError => e
    Bugsnag.notify(e)
    flash[:error] = e.message
    redirect_to new_course_purchase_path(params[:course_id])
  end
end

app/views/subscriptions/create.html.erb
<main class="m-0a xw-64r d-f jc-c p-2">
  <div class="box p-4@mn p-6@md" style="border-radius: 1rem; max-width: 30em">
    <h1 class="mt-0">Thanks for your support!</h1>

    <p>
      I love to make training content for the React community.
      Your support is making that possible.
    </p>

    <p>
      In addition to this site, your support keeps references like
      <a href="https://reactpatterns.com" target="_blank">reactpatterns.com</a>,
      <a href="https://reactcheatsheet.com" target="_blank">reactcheatsheet.com</a>,
      ond <a href="https://react.holiday" target="_blank">react.holiday</a> running.
    </p>

    <p>
      💖 <a href="https://twitter.com/chantastic" targte="_blank">chantastic</a>
    </p>

    <hr class="my-4" style="border-style: solid; border-width: 1px 0; border-color: #eee" />

    <%= link_to "Go the courses", courses_path %>
  </div>
</main>

app/views/subscriptions/new.html.erb
<main class="m-0a xw-64r d-f jc-c p-2">
  <%# TODO: add check for status %>
  <% if current_user.present? && current_user.subscription.present? %>
    <div>
      <h1>You good.</h1>
      <%# TODO: LOL, make this real %>
      <p>
        You've got until <%= (current_user.subscription.created_at + 1.years).strftime("%x") %>.
      </p>
      <p>
        I'll let you know when it's coming up.
      </p>
    </div>
  <% elseif false %>
    <div class="box p-4@mn p-6@md" style="border-radius: 1rem; max-width: 30em">
      <h2 class="o-h fw-900 mt-0 c-blue mb-1" style="font-size: 2rem">We've moved!</h2>
      <h2 class="o-h mt-0 fw-400 c-black7"><em><strong class="c-blue">$36</strong> for 1 year</em></h2>

      <hr style="border-style: solid; border-width: 1px 0; border-color: #eee" />

      <p>
        Subscribe today and get access to these courses for one year:
      </p>

      <ul style="padding-left: 1em; line-height: 1.5em">
        <li><a href="https://learnreact.com/lessons/2018-essential-react-1-overview" target="_blank">Essential React</a></li> 
        <li><a href="https://learnreact.com/lessons/react-function-components-get-started" target="_blank">Function Components</a></li>
        <li><a href="https://learnreact.com/lessons/2017-react-style-with-components-get-started" target="_blank">Style with Components</a></li>
      </ul>

      <h3>Bonus</h3>
      <p>
        Everything I make in 2018 is included for free 🎉
      </p>

      <hr style="border-style: solid; border-width: 1px 0; border-color: #eee" />

      <div class="pt-4">
        <% if current_user.present? %>
          <%= form_tag subscriptions_path, class: "ta-c" do %>
            <script
              src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Subscription for 1 year"
              data-name="Learn React Subscription"
              data-amount="3600"
              data-locale="auto"
              data-label="Subscribe for $36"
            ></script>
          <% end %>
        <% else %>
          <div class="ta-c">
            <%# link_to 'Log in to buy...', signin_path, class: "btn buy-btn", "data-turbolinks": false %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="box p-4@mn p-6@md" style="border-radius: 1rem; max-width: 30em">
    <h2 class="o-h fw-900 mt-0 c-blue mb-1" style="font-size: 2rem">We're moving!</h2>
    <br />
    <h2 class="o-h mt-0 fw-400 c-black7">
      Get <em><strong class="c-blue">50%</strong> at reactpatterns.com.</em>
    </h2>

    <br />

    <div style="text-align:center">
    <a target="_blank" rel="noreferrer" style="font-size: 1.2rem" class="btn buy-btn" href="https://school.reactpatterns.com/p/subscription/?product_id=705894&coupon_code=2018SWITCH">Buy on reactpatterns.com</a>
    </div>
  <% end %>
</main>

app/views/subscriptions/successful.html.erb
<main class="m-0a xw-64r d-f jc-c p-2">
  <div class="box p-4@mn p-6@md" style="border-radius: 1rem; max-width: 30em">
    <h1 class="mt-0">Thanks for your support!</h1>

    <p>
      I love to make training content for the React community.
      Your support is making that possible.
    </p>

    <p>
      In addition to this site, your support keeps references like
      <a href="https://reactpatterns.com" target="_blank">reactpatterns.com</a>,
      <a href="https://reactcheatsheet.com" target="_blank">reactcheatsheet.com</a>,
      ond <a href="https://react.holiday" target="_blank">react.holiday</a> running.
    </p>

    <p>
      💖 <a href="https://twitter.com/chantastic" targte="_blank">chantastic</a>
    </p>

    <hr class="my-4" style="border-style: solid; border-width: 1px 0; border-color: #eee" />

    <%= link_to "Go the courses", courses_path %>
  </div>
</main>