config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :courses
    resources :lessons
    resources :purchases
  end

  resources :courses, only: [:index, :show] do
    scope module: "courses" do
      resources :purchases, only: [:new, :create]
    end
  end
  resources :lessons, only: [:index, :show]
  resources :purchases, only: [:index]
  resources :subscriptions, only: [:new] do
    get 'successful', on: :new # REST exception for analytics tracking
  end

  namespace :my do
    resource :subscription, only: [:show]
  end

  namespace :stripe do
    resources :webhook, only: :create
  end

  root "courses#index"

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates_presence_of :slug

  def self.default_scope
    order(created_at: :asc)
  end

  def to_param
    "#{slug}"
  end
end

app/controllers/admin/lessons_controller.rb
module Admin
  class LessonsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Lesson.
    #     page(params[:page]).
    #     per(10)
    # end

    def find_resource(param)
      Lesson.find_by!(slug: param)
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  include SessionsHelper

  before_action :set_session_return_to

  def show
    @lesson = Lesson.find_by!(slug: params[:id])
  end

  def index
    @lessons = Lesson.all()
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_current_lesson.html.erb
<div class="f-l w-50%@mn w-25%@md w-20%@lg p-1">
  <div style="height: 175px;" class="d-f fd-c w-100% ow-1p p-2 gc-black7">
    <div class="d-b black fg-1 fs-1 fb-0% c-white ">
      You are here.
    </div>
  </div>
</div>

app/views/lessons/_lesson.html.erb
<div class="f-l w-50%@mn w-25%@md w-20%@lg p-1">
  <%= link_to lesson, class: "d-b c-black td-n td-u:h", title: "#{lesson.title} on learnreact.com" do %>
    <div style="height: 175px;" class="ow-1p p-2">
      <%= lesson.title %>
    </div>
  <% end %>
</div>

app/views/lessons/index.html.erb
<main class="mw8 center">
  <div class="cf p-1">
    <%= render(partial: "lesson", collection: @lessons) || "No lessons." %>
  </div>
</main>

app/views/lessons/show.html.erb
<main class="p-2 xw-64r m-0a">
  <div>
    <h4 class="m-0 mb-1 fw-n">
      <%= link_to course_path(@lesson.course), class: "c-black td-n td-u:h" do %>
        <%= @lesson.course.title %>:
      <% end %>
    </h4>

    <h4 class="mt-0">
      <%= @lesson.title %>
    </h4>


    <div class="ow-1p">
      <% if @lesson.free || ContentAccessUser.new(current_user).can_access_lesson?(@lesson) %>
        <%= @lesson.video_embed.html_safe %>
      <% else %>
        <div>
          <div class="d-f fd-c ai-c t-0 jc-c l-0 df-c p-4" style="height: 100%">
            <h2 class="font-size-1 m-0a fw-b">
              You need a subscription!
            </h2>

            <br />

            <p style="text-align: center">
              Subscribe now and get access to <strong>all</strong> courses for <strong>1 year</strong>.
            </p>

            <br />

            <div class="m-0a p-2">
              <%= link_to 'Subscribe for $36', new_subscription_path, class: "btn buy-btn" %>
            </div>


            <% if !user_signed_in? %>
              <p>
                Already a subscriber? <%= link_to 'Log in', signin_path %>
              </p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

  </div>

  <% if @lesson.free && !ContentAccessUser.new(current_user).has_subscription? %>
    <div class="py-2">
      <%= link_to 'Subscribe', new_subscription_path, class: "btn buy-btn" %>
    </div>
  <% end %>

  <% if user_chan? %>
    <div class="py-2">
      <%= link_to "Admin lesson", edit_admin_lesson_path(@lesson), class: "btn", "data-turbolinks": false %>
    </div>
  <% end %>
</main>

<div class="xw-64r m-0a">
  <div class="cf p-1">
    <% @lesson.course.lessons.each do |lesson| %>
      <% if lesson.id == @lesson.id %>
        <%= render partial: "current_lesson", locals: { lesson: lesson } %>
        <% else %>
        <%= render partial: "lesson", locals: { lesson: lesson } %>
      <% end %>
    <% end %>
  </div>
</div>